"""empty message

Revision ID: 03cd5ce6ba5e
Revises: 34e1664bad05
Create Date: 2020-06-16 12:46:04.325724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03cd5ce6ba5e'
down_revision = '34e1664bad05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('volume_is_low', sa.Boolean(), nullable=True),
    sa.Column('volume_is_high', sa.Boolean(), nullable=True),
    sa.Column('recording_has_glitch', sa.Boolean(), nullable=True),
    sa.Column('recording_has_wrong_wording', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('is_secondary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['Recording.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Trim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('end', sa.Float(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['Verification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('trim')
    op.drop_table('verification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume_is_low', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('volume_is_high', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recording_has_glitch', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recording_has_wrong_wording', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recording_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_secondary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['Recording.id'], name='verification_recording_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], name='verification_verified_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='verification_pkey')
    )
    op.create_table('trim',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('start', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('end', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trim_pkey')
    )
    op.drop_table('Trim')
    op.drop_table('Verification')
    # ### end Alembic commands ###
