"""empty message

Revision ID: 044a0f51d260
Revises: 37a95f6fac10
Create Date: 2019-11-26 01:53:10.799490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044a0f51d260'
down_revision = '37a95f6fac10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Rating_user_id_fkey', 'Rating', type_='foreignkey')
    op.create_foreign_key(None, 'Rating', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('Recording_user_id_fkey', 'Recording', type_='foreignkey')
    op.create_foreign_key(None, 'Recording', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('Session_user_id_fkey', 'Session', type_='foreignkey')
    op.create_foreign_key(None, 'Session', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Session', type_='foreignkey')
    op.create_foreign_key('Session_user_id_fkey', 'Session', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'Recording', type_='foreignkey')
    op.create_foreign_key('Recording_user_id_fkey', 'Recording', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'Rating', type_='foreignkey')
    op.create_foreign_key('Rating_user_id_fkey', 'Rating', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
