"""empty message

Revision ID: 069a4549b999
Revises: 12a9fdc66317
Create Date: 2021-01-29 13:59:02.441588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069a4549b999'
down_revision = '12a9fdc66317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mos', sa.Column('num_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Mos', 'num_participants')
    # ### end Alembic commands ###
