"""empty message

Revision ID: 080b80162f3e
Revises: b873b44b3709
Create Date: 2019-11-12 13:00:31.640892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080b80162f3e'
down_revision = 'b873b44b3709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('marked_as_bad', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recording', 'marked_as_bad')
    # ### end Alembic commands ###
