"""empty message

Revision ID: 0c73aa7cc580
Revises: 328410ca6c55
Create Date: 2020-07-09 02:43:26.663224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c73aa7cc580'
down_revision = '328410ca6c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Application', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('Application', sa.Column('uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Application', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Application', type_='foreignkey')
    op.drop_column('Application', 'uuid')
    op.drop_column('Application', 'user_id')
    # ### end Alembic commands ###
