"""empty message

Revision ID: 0ca0bec0893f
Revises: b15f33c4e6f5
Create Date: 2020-08-31 16:00:19.285889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca0bec0893f'
down_revision = 'b15f33c4e6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mos', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Mos', 'uuid')
    # ### end Alembic commands ###
