"""empty message

Revision ID: 0e275b62e9de
Revises: b5fb0d9eb47e
Create Date: 2020-07-11 03:07:13.971328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e275b62e9de'
down_revision = 'b5fb0d9eb47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('verifier_lootbox')
    #op.drop_table('progression_lootbox')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('progression_lootbox',
    #sa.Column('progression_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('lootbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.ForeignKeyConstraint(['lootbox_id'], ['verifier_lootbox.id'], name='progression_lootbox_lootbox_id_fkey'),
    #sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], name='progression_lootbox_progression_id_fkey')
    #)
    #op.create_table('verifier_lootbox',
    #sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('rarity', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('id', name='verifier_lootbox_pkey')
    #)
    # ### end Alembic commands ###
    pass