"""empty message

Revision ID: 12c095eb7e22
Revises: c714bb3ce557
Create Date: 2019-08-18 21:47:30.293231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c095eb7e22'
down_revision = 'c714bb3ce557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('Recording', sa.Column('num_channels', sa.Integer(), nullable=True))
    op.add_column('Recording', sa.Column('num_frames', sa.Integer(), nullable=True))
    op.add_column('Recording', sa.Column('sr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recording', 'sr')
    op.drop_column('Recording', 'num_frames')
    op.drop_column('Recording', 'num_channels')
    op.drop_column('Recording', 'duration')
    # ### end Alembic commands ###
