"""empty message

Revision ID: 16a756d75029
Revises: 51c5e3c27ddd
Create Date: 2019-08-20 17:43:45.814740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a756d75029'
down_revision = '51c5e3c27ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Recording', 'user', new_column_name='user_id')

def downgrade():
    op.alter_column('Recording', 'user_id', new_column_name='user')
