"""empty message

Revision ID: 194c11944003
Revises: 2c18a6159747
Create Date: 2020-02-06 17:25:26.801059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194c11944003'
down_revision = '2c18a6159747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('num_invalid_tokens', sa.Integer(), nullable=True))
    op.add_column('Collection', sa.Column('num_recorded_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'num_recorded_tokens')
    op.drop_column('Collection', 'num_invalid_tokens')
    # ### end Alembic commands ###
