"""empty message

Revision ID: 1a3fe32041b8
Revises: 7bcc011d0045
Create Date: 2020-07-14 09:39:34.151068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3fe32041b8'
down_revision = '7bcc011d0045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('equipped_font_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'verifier_progression', 'verifier_font', ['equipped_font_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifier_progression', type_='foreignkey')
    op.drop_column('verifier_progression', 'equipped_font_id')
    # ### end Alembic commands ###
