"""empty message

Revision ID: 1bfe5b6c9406
Revises: bdc73ef927b7
Create Date: 2019-08-11 19:10:25.805465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfe5b6c9406'
down_revision = 'bdc73ef927b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token'], ['Token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recording')
    # ### end Alembic commands ###
