"""empty message

Revision ID: 2012fdbb59b1
Revises: f41232bd50d7
Create Date: 2021-06-01 17:25:38.451068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2012fdbb59b1'
down_revision = 'f41232bd50d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_item', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_font', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_icon', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_quote', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_title', sa.Column('for_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_title', 'for_sale')
    op.drop_column('verifier_quote', 'for_sale')
    op.drop_column('verifier_icon', 'for_sale')
    op.drop_column('verifier_font', 'for_sale')
    op.drop_column('premium_item', 'for_sale')
    # ### end Alembic commands ###
