"""empty message

Revision ID: 26eb1d59ef5d
Revises: 88198f3b5133
Create Date: 2020-07-07 18:29:59.985034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26eb1d59ef5d'
down_revision = '88198f3b5133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_icon', sa.Column('fa_id', sa.String(), nullable=True))
    op.drop_column('verifier_icon', 'Font Awesome ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_icon', sa.Column('Font Awesome ID', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('verifier_icon', 'fa_id')
    # ### end Alembic commands ###
