"""empty message

Revision ID: 27ce7cefff5f
Revises: 7694e135cbee
Create Date: 2020-07-30 18:24:15.467845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ce7cefff5f'
down_revision = '7694e135cbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('is_synth', sa.Boolean(), nullable=True))
    op.add_column('MosInstance', sa.Column('path', sa.String(), nullable=True))
    op.add_column('MosInstance', sa.Column('selected', sa.Boolean(), nullable=True))
    op.add_column('MosInstance', sa.Column('text', sa.String(), nullable=True))
    op.drop_column('MosInstance', 'ground_truth_selected')
    op.drop_column('MosInstance', 'synth_selected')
    op.drop_column('MosInstance', 'synthesized_audio_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('synthesized_audio_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('MosInstance', sa.Column('synth_selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('MosInstance', sa.Column('ground_truth_selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('MosInstance', 'text')
    op.drop_column('MosInstance', 'selected')
    op.drop_column('MosInstance', 'path')
    op.drop_column('MosInstance', 'is_synth')
    # ### end Alembic commands ###
