"""empty message

Revision ID: 293be2f1d502
Revises: 960a68574a98
Create Date: 2019-08-12 16:20:31.485477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '293be2f1d502'
down_revision = '960a68574a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'confirmed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'name')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
