"""empty message

Revision ID: 2973363eeb50
Revises: 6df2c1422fb3
Create Date: 2020-07-16 15:14:54.531002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2973363eeb50'
down_revision = '6df2c1422fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('fire_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_progression', sa.Column('fire_sale_discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'fire_sale_discount')
    op.drop_column('verifier_progression', 'fire_sale')
    # ### end Alembic commands ###
