"""empty message

Revision ID: 29c8ab27222c
Revises: b7b8ba124db7
Create Date: 2019-08-10 22:14:23.040737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c8ab27222c'
down_revision = 'b7b8ba124db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('original_fname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'original_fname')
    # ### end Alembic commands ###
