"""empty message

Revision ID: 2ba5255eb0a6
Revises: 044a0f51d260
Create Date: 2019-11-29 01:33:29.722369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba5255eb0a6'
down_revision = '044a0f51d260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'active')
    # ### end Alembic commands ###
