"""empty message

Revision ID: 2c18a6159747
Revises: d25d983bb90f
Create Date: 2020-02-06 17:19:50.238146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c18a6159747'
down_revision = 'd25d983bb90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('num_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'num_tokens')
    # ### end Alembic commands ###
