"""empty message

Revision ID: 2fb9d5ceff23
Revises: c9b01a0c4f1a
Create Date: 2019-11-05 10:01:54.192437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb9d5ceff23'
down_revision = 'c9b01a0c4f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('marked_as_bad', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'marked_as_bad')
    # ### end Alembic commands ###
