"""empty message

Revision ID: 310bd2e40d2c
Revises: 96068c645312
Create Date: 2020-07-14 09:57:24.543951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310bd2e40d2c'
down_revision = '96068c645312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_font', sa.Column('font_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_font', 'font_type')
    # ### end Alembic commands ###
