"""empty message

Revision ID: 328410ca6c55
Revises: 38ca7c85f68f
Create Date: 2020-07-09 00:15:14.234728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328410ca6c55'
down_revision = '38ca7c85f68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ad_text', sa.String(), nullable=True),
    sa.Column('utterances', sa.String(), nullable=True),
    sa.Column('collection', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('voice', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['Posting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Collection', sa.Column('is_multi_speaker', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'is_multi_speaker')
    op.drop_table('Application')
    op.drop_table('Posting')
    # ### end Alembic commands ###
