"""empty message

Revision ID: 34e1664bad05
Revises: 317a951676a1
Create Date: 2020-06-16 12:36:58.754332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e1664bad05'
down_revision = '317a951676a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trim', sa.Column('index', sa.Integer(), nullable=True))
    op.drop_constraint('trim_recording_id_fkey', 'trim', type_='foreignkey')
    op.drop_column('trim', 'recording_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trim', sa.Column('recording_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trim_recording_id_fkey', 'trim', 'Recording', ['recording_id'], ['id'])
    op.drop_column('trim', 'index')
    # ### end Alembic commands ###
