"""empty message

Revision ID: 38ca7c85f68f
Revises: 03cd5ce6ba5e
Create Date: 2020-06-19 18:03:24.102421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ca7c85f68f'
down_revision = '03cd5ce6ba5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('is_secondarily_verified', sa.Boolean(), nullable=True))
    op.add_column('Recording', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recording', 'is_verified')
    op.drop_column('Recording', 'is_secondarily_verified')
    # ### end Alembic commands ###
