"""empty message

Revision ID: 392cc923f7cc
Revises: 2daf67ed4b63
Create Date: 2020-07-08 19:03:33.324929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392cc923f7cc'
down_revision = '2daf67ed4b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('equipped_icon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'verifier_progression', 'verifier_icon', ['equipped_icon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifier_progression', type_='foreignkey')
    op.drop_column('verifier_progression', 'equipped_icon_id')
    # ### end Alembic commands ###
