"""empty message

Revision ID: 396445290990
Revises: 080b80162f3e
Create Date: 2019-11-21 15:06:36.745871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396445290990'
down_revision = '080b80162f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('bit_depth', sa.Integer(), nullable=True))
    op.add_column('Recording', sa.Column('file_id', sa.String(), nullable=True))
    op.add_column('Recording', sa.Column('plot_fname', sa.String(), nullable=True))
    op.add_column('Recording', sa.Column('plot_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recording', 'plot_path')
    op.drop_column('Recording', 'plot_fname')
    op.drop_column('Recording', 'file_id')
    op.drop_column('Recording', 'bit_depth')
    # ### end Alembic commands ###
