"""empty message

Revision ID: 3a3e25415df0
Revises: c2e6f3a56bbe
Create Date: 2019-08-13 20:59:14.057999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3e25415df0'
down_revision = 'c2e6f3a56bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('has_recording', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'has_recording')
    # ### end Alembic commands ###
