"""empty message

Revision ID: 3cf6ea920d09
Revises: aab27b601153
Create Date: 2019-11-05 10:38:31.934733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf6ea920d09'
down_revision = 'aab27b601153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Session', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Session', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Session', type_='foreignkey')
    op.drop_column('Session', 'user_id')
    op.drop_column('Session', 'created_at')
    # ### end Alembic commands ###
