"""empty message

Revision ID: 478fbc59bc54
Revises: db9ee02ae47e
Create Date: 2020-06-15 19:58:35.861905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478fbc59bc54'
down_revision = 'db9ee02ae47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'is_verified')
    # ### end Alembic commands ###
