"""empty message

Revision ID: 4fae19a558c4
Revises: e57893fa344a
Create Date: 2020-07-08 23:15:16.906172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fae19a558c4'
down_revision = 'e57893fa344a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('spy_level', sa.Integer(), nullable=True))
    op.add_column('verifier_progression', sa.Column('streak_level', sa.Integer(), nullable=True))
    op.add_column('verifier_progression', sa.Column('verification_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'verification_level')
    op.drop_column('verifier_progression', 'streak_level')
    op.drop_column('verifier_progression', 'spy_level')
    # ### end Alembic commands ###
