"""empty message

Revision ID: 51c5e3c27ddd
Revises: 795582c3835d
Create Date: 2019-08-19 23:05:11.924061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c5e3c27ddd'
down_revision = '795582c3835d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('sr', sa.Integer(), nullable=True),
    sa.Column('num_channels', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('num_frames', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['Token.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recording')
    op.drop_table('Token')
    op.drop_table('Collection')
    # ### end Alembic commands ###
