"""empty message

Revision ID: 562ef4bb68cc
Revises: f8b54ff0e756
Create Date: 2020-02-12 16:26:41.648132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562ef4bb68cc'
down_revision = 'f8b54ff0e756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pin', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
