"""empty message

Revision ID: 59632726c183
Revises: 9c830a383d75
Create Date: 2020-07-02 13:26:35.715266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59632726c183'
down_revision = '9c830a383d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('is_dev', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'is_dev')
    # ### end Alembic commands ###
