"""empty message

Revision ID: 5969d8aad04f
Revises: c74ae03c2ec6
Create Date: 2020-07-08 16:06:02.243222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5969d8aad04f'
down_revision = 'c74ae03c2ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_icon', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_icon', 'color')
    # ### end Alembic commands ###
