"""empty message

Revision ID: 5ab9d2d0c181
Revises: b31c87c6bf74
Create Date: 2020-06-15 19:54:27.726630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab9d2d0c181'
down_revision = 'b31c87c6bf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('volume_is_low', sa.Boolean(), nullable=True),
    sa.Column('volume_is_high', sa.Boolean(), nullable=True),
    sa.Column('recording_has_glitch', sa.Boolean(), nullable=True),
    sa.Column('recording_has_wrong_wording', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    # ### end Alembic commands ###
