"""empty message

Revision ID: 5bf1deecbf3b
Revises: e249bce65b4b
Create Date: 2020-09-03 16:16:55.289920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf1deecbf3b'
down_revision = 'e249bce65b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MosInstance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mos_id', sa.Integer(), nullable=True),
    sa.Column('is_synth', sa.Boolean(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mos_id'], ['Mos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CustomRecording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('copied_recording', sa.Boolean(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('wav_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CustomToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('copied_token', sa.Boolean(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('marked_as_bad', sa.Boolean(), nullable=True),
    sa.Column('pron', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MosRating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mos_instance_id', 'user_id')
    )
    #op.drop_table('progression_lootbox')
    #op.drop_table('verifier_lootbox')
    op.add_column('user', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('user', 'uuid')
    #op.create_table('verifier_lootbox',
    #sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('verifier_lootbox_id_seq'::regclass)"), autoincrement=True, nullable=False),
    #sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('rarity', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('id', name='verifier_lootbox_pkey'),
    #postgresql_ignore_search_path=False
    #)
    #op.create_table('progression_lootbox',
    #sa.Column('progression_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('lootbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.ForeignKeyConstraint(['lootbox_id'], ['verifier_lootbox.id'], name='progression_lootbox_lootbox_id_fkey'),
    #sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], name='progression_lootbox_progression_id_fkey')
    #)
    op.drop_table('MosRating')
    op.drop_table('CustomToken')
    op.drop_table('CustomRecording')
    op.drop_table('MosInstance')
    op.drop_table('Mos')
    # ### end Alembic commands ###
