"""empty message

Revision ID: 60d60eb59f58
Revises: 0e275b62e9de
Create Date: 2020-07-11 19:03:33.578086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d60eb59f58'
down_revision = '0e275b62e9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('last_spin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'last_spin')
    # ### end Alembic commands ###
