"""empty message

Revision ID: 6301e7544fe0
Revises: 478fbc59bc54
Create Date: 2020-06-15 20:58:54.789083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6301e7544fe0'
down_revision = '478fbc59bc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('is_secondarily_verified', sa.Boolean(), nullable=True))
    op.add_column('Session', sa.Column('secondarily_verified_by', sa.Integer(), nullable=True))
    op.add_column('Session', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Session', 'user', ['secondarily_verified_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Session', 'user', ['verified_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Session', type_='foreignkey')
    op.drop_constraint(None, 'Session', type_='foreignkey')
    op.drop_column('Session', 'verified_by')
    op.drop_column('Session', 'secondarily_verified_by')
    op.drop_column('Session', 'is_secondarily_verified')
    # ### end Alembic commands ###
