"""empty message

Revision ID: 741e6dd28e3f
Revises: 06ca60822309
Create Date: 2020-08-12 16:37:50.334426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741e6dd28e3f'
down_revision = '06ca60822309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosRating', sa.Column('mosInastance_id', sa.Integer(), nullable=True))
    op.drop_constraint('MosRating_MosInastance_id_fkey', 'MosRating', type_='foreignkey')
    op.create_foreign_key(None, 'MosRating', 'MosInstance', ['mosInastance_id'], ['id'])
    op.drop_column('MosRating', 'MosInastance_id')
    op.drop_column('SynthToken', 'num_recordings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SynthToken', sa.Column('num_recordings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('MosRating', sa.Column('MosInastance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'MosRating', type_='foreignkey')
    op.create_foreign_key('MosRating_MosInastance_id_fkey', 'MosRating', 'MosInstance', ['MosInastance_id'], ['id'])
    op.drop_column('MosRating', 'mosInastance_id')
    # ### end Alembic commands ###
