"""empty message

Revision ID: 7490c27b4d46
Revises: 075d9befea14
Create Date: 2019-11-25 20:37:55.736541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7490c27b4d46'
down_revision = '075d9befea14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Collection', 'user', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Collection', type_='foreignkey')
    op.drop_column('Collection', 'assigned_user_id')
    # ### end Alembic commands ###
