"""empty message

Revision ID: 759cd04e2408
Revises: 4fae19a558c4
Create Date: 2020-07-09 13:27:40.348649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759cd04e2408'
down_revision = '4fae19a558c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_icon', sa.Column('rarity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_icon', 'rarity')
    # ### end Alembic commands ###
