"""empty message

Revision ID: 7694e135cbee
Revises: ea6ccccd864d
Create Date: 2020-07-21 15:34:48.964493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7694e135cbee'
down_revision = 'ea6ccccd864d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('ground_truth_selected', sa.Boolean(), nullable=True))
    op.add_column('MosInstance', sa.Column('synth_selected', sa.Boolean(), nullable=True))
    op.drop_column('MosInstance', 'mos_selected')
    op.drop_column('MosInstance', 'mos_instance_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('mos_instance_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('MosInstance', sa.Column('mos_selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('MosInstance', 'synth_selected')
    op.drop_column('MosInstance', 'ground_truth_selected')
    # ### end Alembic commands ###
