"""empty message

Revision ID: 780d1ad18bcd
Revises: 392cc923f7cc
Create Date: 2020-07-08 19:15:09.381412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780d1ad18bcd'
down_revision = '392cc923f7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('equipped_title_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'verifier_progression', 'verifier_title', ['equipped_title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifier_progression', type_='foreignkey')
    op.drop_column('verifier_progression', 'equipped_title_id')
    # ### end Alembic commands ###
