"""empty message

Revision ID: 795582c3835d
Revises: b69c2c99fe41
Create Date: 2019-08-19 22:53:52.540667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795582c3835d'
down_revision = 'b69c2c99fe41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('token_id', sa.Integer(), nullable=True))
    op.drop_constraint('Recording_token_fkey', 'Recording', type_='foreignkey')
    op.create_foreign_key(None, 'Recording', 'Token', ['token_id'], ['id'])
    op.drop_column('Recording', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Recording', type_='foreignkey')
    op.create_foreign_key('Recording_token_fkey', 'Recording', 'Token', ['token'], ['id'])
    op.drop_column('Recording', 'token_id')
    # ### end Alembic commands ###
