"""empty message

Revision ID: 799245572a4e
Revises: 802fc2cdb495
Create Date: 2020-07-11 00:14:07.830260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799245572a4e'
down_revision = '802fc2cdb495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('has_seen_weekly_prices', sa.Boolean(), nullable=True))
    op.add_column('verifier_progression', sa.Column('weekly_coin_price', sa.Integer(), nullable=True))
    op.add_column('verifier_progression', sa.Column('weekly_experience_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'weekly_experience_price')
    op.drop_column('verifier_progression', 'weekly_coin_price')
    op.drop_column('verifier_progression', 'has_seen_weekly_prices')
    # ### end Alembic commands ###
