"""empty message

Revision ID: 7bcc011d0045
Revises: d45a8fe327c6
Create Date: 2020-07-14 09:30:34.530546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcc011d0045'
down_revision = 'd45a8fe327c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifier_font',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progression_font',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('font_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['font_id'], ['verifier_font.id'], ),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], )
    )
    op.drop_column('verifier_progression', 'equipped_font')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('equipped_font', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('progression_font')
    op.drop_table('verifier_font')
    # ### end Alembic commands ###
