"""empty message

Revision ID: 7d2caca954f8
Revises: 1bfe5b6c9406
Create Date: 2019-08-11 19:57:29.836866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2caca954f8'
down_revision = '1bfe5b6c9406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('Recording', sa.Column('fname', sa.String(), nullable=True))
    op.add_column('Recording', sa.Column('original_fname', sa.String(), nullable=True))
    op.add_column('Recording', sa.Column('path', sa.String(), nullable=True))
    op.add_column('Token', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'created_at')
    op.drop_column('Recording', 'path')
    op.drop_column('Recording', 'original_fname')
    op.drop_column('Recording', 'fname')
    op.drop_column('Recording', 'created_at')
    # ### end Alembic commands ###
