"""empty message

Revision ID: 802fc2cdb495
Revises: b7ae2ad2d5dd
Create Date: 2020-07-10 23:37:34.175111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802fc2cdb495'
down_revision = 'b7ae2ad2d5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('weekly_verifies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'weekly_verifies')
    # ### end Alembic commands ###
