"""empty message

Revision ID: 80530ea60e18
Revises: a6d9c73d0530
Create Date: 2021-01-27 22:38:48.684242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80530ea60e18'
down_revision = 'a6d9c73d0530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mos', sa.Column('form_text', sa.String(), nullable=True))
    op.add_column('Mos', sa.Column('help_text', sa.String(), nullable=True))
    op.add_column('Mos', sa.Column('question', sa.String(), nullable=True))
    op.drop_column('Mos', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mos', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Mos', 'question')
    op.drop_column('Mos', 'help_text')
    op.drop_column('Mos', 'form_text')
    # ### end Alembic commands ###
