"""empty message

Revision ID: 807b33c30918
Revises: 60d60eb59f58
Create Date: 2020-07-13 15:41:09.163421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807b33c30918'
down_revision = '60d60eb59f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mos')
    # ### end Alembic commands ###
