"""empty message

Revision ID: 87a546a6d0df
Revises: 12c095eb7e22
Create Date: 2019-08-18 23:46:12.034223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a546a6d0df'
down_revision = '12c095eb7e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('transcription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recording', 'transcription')
    # ### end Alembic commands ###
