"""empty message

Revision ID: 8cd8c82d90ee
Revises: a9d8df10e1dd
Create Date: 2021-06-01 18:32:27.989644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd8c82d90ee'
down_revision = 'a9d8df10e1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('verify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'verify')
    # ### end Alembic commands ###
