"""empty message

Revision ID: 9099ee53900a
Revises: af79e90597fe
Create Date: 2020-08-05 17:42:34.030275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9099ee53900a'
down_revision = 'af79e90597fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Synth', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Synth', 'text')
    # ### end Alembic commands ###
