"""empty message

Revision ID: 91ca96ec04e7
Revises: 87a546a6d0df
Create Date: 2019-08-19 22:42:15.066812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91ca96ec04e7'
down_revision = '87a546a6d0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Collection', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Collection', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Recording', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Recording', 'token',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Token', 'collection',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Token', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Token', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Token', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Token', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Token', 'collection',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Recording', 'token',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Recording', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Collection', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Collection', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
