"""empty message

Revision ID: 91db308e3dc8
Revises: fdc3275f48bf
Create Date: 2020-07-14 09:50:47.008590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91db308e3dc8'
down_revision = 'fdc3275f48bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_font', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_font', 'description')
    # ### end Alembic commands ###
