"""empty message

Revision ID: 95161025e63c
Revises: ccfd919ae4b8
Create Date: 2020-01-30 16:23:08.229943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95161025e63c'
down_revision = 'ccfd919ae4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('has_video', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'has_video')
    # ### end Alembic commands ###
