"""empty message

Revision ID: 954140d6b159
Revises: 069a4549b999
Create Date: 2021-01-29 15:21:26.679711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954140d6b159'
down_revision = '069a4549b999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('MosInstance', sa.Column('utterance_idx', sa.Integer(), nullable=True))
    op.add_column('MosInstance', sa.Column('voice_idx', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MosInstance', 'voice_idx')
    op.drop_column('MosInstance', 'utterance_idx')
    op.drop_column('MosInstance', 'question')
    # ### end Alembic commands ###
