"""empty message

Revision ID: 96068c645312
Revises: 91db308e3dc8
Create Date: 2020-07-14 09:54:31.600145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96068c645312'
down_revision = '91db308e3dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_font', sa.Column('href', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_font', 'href')
    # ### end Alembic commands ###
