"""empty message

Revision ID: 9806580aec8b
Revises: b5701d900296
Create Date: 2020-07-08 17:07:39.628186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9806580aec8b'
down_revision = 'b5701d900296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_quote',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['verifier_quote.id'], )
    )
    op.create_table('progression_title',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['verifier_title.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progression_title')
    op.drop_table('progression_quote')
    # ### end Alembic commands ###
