"""empty message

Revision ID: 99a09cff2e7e
Revises: 780d1ad18bcd
Create Date: 2020-07-08 21:32:59.118209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a09cff2e7e'
down_revision = '780d1ad18bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('equipped_quote_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'verifier_progression', 'verifier_quote', ['equipped_quote_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifier_progression', type_='foreignkey')
    op.drop_column('verifier_progression', 'equipped_quote_id')
    # ### end Alembic commands ###
