"""empty message

Revision ID: 9bcbe67560e7
Revises: 824944051a41
Create Date: 2019-11-07 22:45:22.239207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcbe67560e7'
down_revision = '824944051a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'duration')
    # ### end Alembic commands ###
