"""empty message

Revision ID: 9c830a383d75
Revises: 38ca7c85f68f
Create Date: 2020-07-02 13:15:20.919953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c830a383d75'
down_revision = '38ca7c85f68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('is_dev', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'is_dev')
    # ### end Alembic commands ###
