"""empty message

Revision ID: a6d9c73d0530
Revises: ed46afb9076b
Create Date: 2021-01-27 04:22:34.238193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d9c73d0530'
down_revision = 'ed46afb9076b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progression_lootbox')
    op.drop_table('verifier_lootbox')
    op.add_column('Mos', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Mos', 'text')
    op.create_table('verifier_lootbox',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('verifier_lootbox_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='verifier_lootbox_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('progression_lootbox',
    sa.Column('progression_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lootbox_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lootbox_id'], ['verifier_lootbox.id'], name='progression_lootbox_lootbox_id_fkey'),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], name='progression_lootbox_progression_id_fkey')
    )
    # ### end Alembic commands ###
