"""empty message

Revision ID: a9d8df10e1dd
Revises: eda5ccefc473
Create Date: 2021-06-01 17:55:00.166716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d8df10e1dd'
down_revision = 'eda5ccefc473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_item', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_font', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_icon', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_quote', sa.Column('for_sale', sa.Boolean(), nullable=True))
    op.add_column('verifier_title', sa.Column('for_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_title', 'for_sale')
    op.drop_column('verifier_quote', 'for_sale')
    op.drop_column('verifier_icon', 'for_sale')
    op.drop_column('verifier_font', 'for_sale')
    op.drop_column('premium_item', 'for_sale')
    # ### end Alembic commands ###
