"""empty message

Revision ID: aab27b601153
Revises: 2fb9d5ceff23
Create Date: 2019-11-05 10:27:59.056935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab27b601153'
down_revision = '2fb9d5ceff23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Recording', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recording', 'Session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recording', type_='foreignkey')
    op.drop_column('Recording', 'session_id')
    op.drop_table('Session')
    # ### end Alembic commands ###
