"""empty message

Revision ID: ab6241a69917
Revises: ad48c9c68560
Create Date: 2019-08-10 00:27:55.597104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6241a69917'
down_revision = 'ad48c9c68560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'name')
    # ### end Alembic commands ###
