"""empty message

Revision ID: af79e90597fe
Revises: 27ce7cefff5f
Create Date: 2020-08-04 16:41:25.469605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af79e90597fe'
down_revision = '27ce7cefff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Synth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('wav_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['Token.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('MosInstance', sa.Column('synth_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'MosInstance', 'Synth', ['synth_id'], ['id'])
    op.add_column('MosRating', sa.Column('placement', sa.Integer(), nullable=True))
    op.drop_column('MosRating', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosRating', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('MosRating', 'placement')
    op.drop_constraint(None, 'MosInstance', type_='foreignkey')
    op.drop_column('MosInstance', 'synth_id')
    op.drop_table('Synth')
    # ### end Alembic commands ###
