"""empty message

Revision ID: b1760222e5e1
Revises: 6301e7544fe0
Create Date: 2020-06-16 08:11:57.767047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1760222e5e1'
down_revision = '6301e7544fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification', sa.Column('is_secondary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification', 'is_secondary')
    # ### end Alembic commands ###
