"""empty message

Revision ID: b31c87c6bf74
Revises: f2ed1a48ec08
Create Date: 2020-04-02 20:08:38.403450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31c87c6bf74'
down_revision = 'f2ed1a48ec08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('zip_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'zip_created_at')
    # ### end Alembic commands ###
