"""empty message

Revision ID: b4e63ee36fe4
Revises: 562ef4bb68cc
Create Date: 2020-02-21 16:19:15.023912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e63ee36fe4'
down_revision = '562ef4bb68cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('has_zip', sa.Boolean(), nullable=True))
    op.add_column('Collection', sa.Column('zip_token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'zip_token_count')
    op.drop_column('Collection', 'has_zip')
    # ### end Alembic commands ###
