"""empty message

Revision ID: b612cc0c2989
Revises: 5730220eb2b0
Create Date: 2020-07-10 16:58:28.098428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b612cc0c2989'
down_revision = '5730220eb2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifier_lootbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progression_lootbox',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('lootbox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lootbox_id'], ['verifier_lootbox.id'], ),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], )
    )
    op.add_column('verifier_progression', sa.Column('num_streak_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'num_streak_days')
    op.drop_table('progression_lootbox')
    op.drop_table('verifier_lootbox')
    # ### end Alembic commands ###
