"""empty message

Revision ID: b7ae2ad2d5dd
Revises: b612cc0c2989
Create Date: 2020-07-10 17:12:57.576129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ae2ad2d5dd'
down_revision = 'b612cc0c2989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('num_session_verifies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'num_session_verifies')
    # ### end Alembic commands ###
