"""empty message

Revision ID: bbd0898cce1c
Revises: 8cd8c82d90ee
Create Date: 2021-06-09 14:29:17.017712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd0898cce1c'
down_revision = '8cd8c82d90ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('age', sa.String(), nullable=True))
    op.add_column('Token', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('Token', sa.Column('natLang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'natLang')
    op.drop_column('Token', 'gender')
    op.drop_column('Token', 'age')
    # ### end Alembic commands ###
