"""empty message

Revision ID: bd6b10aac128
Revises: d9a2cd49a963
Create Date: 2021-05-25 23:59:07.466780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6b10aac128'
down_revision = 'd9a2cd49a963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PrioritySession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('has_priority', sa.Boolean(), nullable=True),
    sa.Column('is_secondarily_verified', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('secondarily_verified_by', sa.Integer(), nullable=True),
    sa.Column('is_dev', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secondarily_verified_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Recording', sa.Column('priority_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recording', 'PrioritySession', ['priority_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recording', type_='foreignkey')
    op.drop_column('Recording', 'priority_session_id')
    op.drop_table('PrioritySession')
    # ### end Alembic commands ###
