"""empty message

Revision ID: bdc73ef927b7
Revises: 29c8ab27222c
Create Date: 2019-08-11 18:06:33.714571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc73ef927b7'
down_revision = '29c8ab27222c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('fname', sa.String(), nullable=True))
    op.add_column('Token', sa.Column('path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'path')
    op.drop_column('Token', 'fname')
    # ### end Alembic commands ###
