"""empty message

Revision ID: c2e6f3a56bbe
Revises: dcbfbfd3f1ce
Create Date: 2019-08-13 16:02:06.925648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e6f3a56bbe'
down_revision = 'dcbfbfd3f1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recording', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Recording', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recording', type_='foreignkey')
    op.drop_column('Recording', 'user')
    # ### end Alembic commands ###
