"""empty message

Revision ID: c4d58be3a67f
Revises: 310bd2e40d2c
Create Date: 2020-07-14 16:51:11.455572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d58be3a67f'
down_revision = '310bd2e40d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'last_spin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('last_spin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
