"""empty message

Revision ID: c714bb3ce557
Revises: 3a3e25415df0
Create Date: 2019-08-13 21:55:26.444335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c714bb3ce557'
down_revision = '3a3e25415df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'has_recording')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('has_recording', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
