"""empty message

Revision ID: c74ae03c2ec6
Revises: 066d1bfdbda6
Create Date: 2020-07-08 16:05:43.536890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74ae03c2ec6'
down_revision = '066d1bfdbda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_icon', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_icon', sa.Column('color', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
