"""empty message

Revision ID: c9b01a0c4f1a
Revises: 7d0dd4210616
Create Date: 2019-11-04 14:30:55.481683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b01a0c4f1a'
down_revision = '7d0dd4210616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pin', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pin')
    # ### end Alembic commands ###
