"""empty message

Revision ID: ccfd919ae4b8
Revises: 3fb71d18d6cf
Create Date: 2019-12-11 14:42:57.621013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfd919ae4b8'
down_revision = '3fb71d18d6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('sort_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'sort_by')
    # ### end Alembic commands ###
