"""empty message

Revision ID: d25d983bb90f
Revises: 95161025e63c
Create Date: 2020-02-06 17:16:29.333426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25d983bb90f'
down_revision = '95161025e63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('has_recording', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'has_recording')
    # ### end Alembic commands ###
