"""empty message

Revision ID: d846d23a96f4
Revises: 97b564bd69fb
Create Date: 2020-02-06 17:49:30.453518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd846d23a96f4'
down_revision = '97b564bd69fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('num_recordings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Token', 'num_recordings')
    # ### end Alembic commands ###
