"""empty message

Revision ID: d9a2cd49a963
Revises: f41232bd50d7
Create Date: 2021-05-25 20:49:41.302863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a2cd49a963'
down_revision = 'f41232bd50d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('has_priority', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'has_priority')
    # ### end Alembic commands ###
