"""empty message

Revision ID: ddebd28b288a
Revises: ab6241a69917
Create Date: 2019-08-10 00:32:58.697355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddebd28b288a'
down_revision = 'ab6241a69917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'created_at')
    # ### end Alembic commands ###
