"""empty message

Revision ID: e249bce65b4b
Revises: 8f3454933a7d
Create Date: 2020-07-21 00:15:11.206959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e249bce65b4b'
down_revision = '8f3454933a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_item', sa.Column('wheel_modifier', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premium_item', 'wheel_modifier')
    # ### end Alembic commands ###
