"""empty message

Revision ID: e3bc9cfe3fb7
Revises: 
Create Date: 2020-08-20 16:37:29.985288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bc9cfe3fb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('session_sz', sa.Integer(), nullable=True),
    sa.Column('live_transcribe', sa.Boolean(), nullable=True),
    sa.Column('visualize_mic', sa.Boolean(), nullable=True),
    sa.Column('auto_trim', sa.Boolean(), nullable=True),
    sa.Column('analyze_sound', sa.Boolean(), nullable=True),
    sa.Column('auto_gain_control', sa.Boolean(), nullable=True),
    sa.Column('noise_suppression', sa.Boolean(), nullable=True),
    sa.Column('channel_count', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('blob_slice', sa.Integer(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('video_w', sa.Integer(), nullable=True),
    sa.Column('video_h', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('trim_threshold', sa.Float(), nullable=True),
    sa.Column('too_low_threshold', sa.Float(), nullable=True),
    sa.Column('too_high_threshold', sa.Float(), nullable=True),
    sa.Column('too_high_frames', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('verifier_font',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('font_family', sa.String(), nullable=True),
    sa.Column('font_type', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifier_icon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fa_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifier_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifier_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifier_progression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_verifies', sa.Integer(), nullable=True),
    sa.Column('num_session_verifies', sa.Integer(), nullable=True),
    sa.Column('num_invalid', sa.Integer(), nullable=True),
    sa.Column('num_streak_days', sa.Integer(), nullable=True),
    sa.Column('weekly_verifies', sa.Integer(), nullable=True),
    sa.Column('weekly_coin_price', sa.Integer(), nullable=True),
    sa.Column('weekly_experience_price', sa.Integer(), nullable=True),
    sa.Column('has_seen_weekly_prices', sa.Boolean(), nullable=True),
    sa.Column('last_spin', sa.DateTime(), nullable=True),
    sa.Column('lobe_coins', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('verification_level', sa.Integer(), nullable=True),
    sa.Column('spy_level', sa.Integer(), nullable=True),
    sa.Column('streak_level', sa.Integer(), nullable=True),
    sa.Column('equipped_icon_id', sa.Integer(), nullable=True),
    sa.Column('equipped_title_id', sa.Integer(), nullable=True),
    sa.Column('equipped_quote_id', sa.Integer(), nullable=True),
    sa.Column('equipped_font_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipped_font_id'], ['verifier_font.id'], ),
    sa.ForeignKeyConstraint(['equipped_icon_id'], ['verifier_icon.id'], ),
    sa.ForeignKeyConstraint(['equipped_quote_id'], ['verifier_quote.id'], ),
    sa.ForeignKeyConstraint(['equipped_title_id'], ['verifier_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progression_font',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('font_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['font_id'], ['verifier_font.id'], ),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], )
    )
    op.create_table('progression_icon',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['verifier_icon.id'], ),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], )
    )
    op.create_table('progression_quote',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['verifier_quote.id'], )
    )
    op.create_table('progression_title',
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['verifier_title.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dialect', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('progression_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['progression_id'], ['verifier_progression.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('is_multi_speaker', sa.Boolean(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort_by', sa.String(), nullable=True),
    sa.Column('num_tokens', sa.Integer(), nullable=True),
    sa.Column('num_recorded_tokens', sa.Integer(), nullable=True),
    sa.Column('num_invalid_tokens', sa.Integer(), nullable=True),
    sa.Column('has_zip', sa.Boolean(), nullable=True),
    sa.Column('zip_token_count', sa.Integer(), nullable=True),
    sa.Column('zip_created_at', sa.DateTime(), nullable=True),
    sa.Column('is_dev', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['Configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('Mos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Posting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ad_text', sa.String(), nullable=True),
    sa.Column('utterances', sa.String(), nullable=True),
    sa.Column('collection', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('is_secondarily_verified', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('secondarily_verified_by', sa.Integer(), nullable=True),
    sa.Column('is_dev', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secondarily_verified_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('marked_as_bad', sa.Boolean(), nullable=True),
    sa.Column('num_recordings', sa.Integer(), nullable=True),
    sa.Column('pron', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('voice', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['Posting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MosInstance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mos_id', sa.Integer(), nullable=True),
    sa.Column('is_synth', sa.Boolean(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mos_id'], ['Mos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('sr', sa.Integer(), nullable=True),
    sa.Column('num_channels', sa.Integer(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('auto_gain_control', sa.Boolean(), nullable=True),
    sa.Column('echo_cancellation', sa.Boolean(), nullable=True),
    sa.Column('noise_suppression', sa.Boolean(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('wav_path', sa.String(), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('end', sa.Float(), nullable=True),
    sa.Column('marked_as_bad', sa.Boolean(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_secondarily_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['Session.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['Token.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CustomRecording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('copied_recording', sa.Boolean(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('wav_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CustomToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('original_fname', sa.String(), nullable=True),
    sa.Column('copied_token', sa.Boolean(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('marked_as_bad', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MosRating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('mos_instance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mos_instance_id'], ['MosInstance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['Recording.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('volume_is_low', sa.Boolean(), nullable=True),
    sa.Column('volume_is_high', sa.Boolean(), nullable=True),
    sa.Column('recording_has_glitch', sa.Boolean(), nullable=True),
    sa.Column('recording_has_wrong_wording', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('is_secondary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['Recording.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Trim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('end', sa.Float(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['Verification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trim')
    op.drop_table('Verification')
    op.drop_table('Rating')
    op.drop_table('MosRating')
    op.drop_table('CustomToken')
    op.drop_table('CustomRecording')
    op.drop_table('Recording')
    op.drop_table('MosInstance')
    op.drop_table('Application')
    op.drop_table('Token')
    op.drop_table('Session')
    op.drop_table('Posting')
    op.drop_table('Mos')
    op.drop_table('roles_users')
    op.drop_table('Collection')
    op.drop_table('user')
    op.drop_table('progression_title')
    op.drop_table('progression_quote')
    op.drop_table('progression_icon')
    op.drop_table('progression_font')
    op.drop_table('verifier_progression')
    op.drop_table('verifier_title')
    op.drop_table('verifier_quote')
    op.drop_table('verifier_icon')
    op.drop_table('verifier_font')
    op.drop_table('role')
    op.drop_table('Configuration')
    # ### end Alembic commands ###
