"""empty message

Revision ID: e57893fa344a
Revises: 99a09cff2e7e
Create Date: 2020-07-08 21:51:09.772302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57893fa344a'
down_revision = '99a09cff2e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_progression', sa.Column('experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_progression', 'experience')
    # ### end Alembic commands ###
