"""empty message

Revision ID: ea6ccccd864d
Revises: 302e9ce12252
Create Date: 2020-07-21 14:09:42.549371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6ccccd864d'
down_revision = '302e9ce12252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MosInstance', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'MosInstance', 'Token', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MosInstance', type_='foreignkey')
    op.drop_column('MosInstance', 'token_id')
    # ### end Alembic commands ###
