"""empty message

Revision ID: ed7eb1a6de1f
Revises: 194c11944003
Create Date: 2020-02-06 17:42:55.086955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7eb1a6de1f'
down_revision = '194c11944003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('num_recordings', sa.Boolean(), nullable=True))
    op.drop_column('Token', 'has_recording')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Token', sa.Column('has_recording', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Token', 'num_recordings')
    # ### end Alembic commands ###
