"""empty message

Revision ID: eda5ccefc473
Revises: bd6b10aac128
Create Date: 2021-06-01 16:52:39.046115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda5ccefc473'
down_revision = 'bd6b10aac128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PrioritySession', 'has_priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PrioritySession', sa.Column('has_priority', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
