"""empty message

Revision ID: f1fa88fa5652
Revises: bbd0898cce1c
Create Date: 2021-06-10 11:07:26.316459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fa88fa5652'
down_revision = 'bbd0898cce1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Verification', sa.Column('metadata_incorrect_age', sa.Boolean(), nullable=True))
    op.add_column('Verification', sa.Column('metadata_incorrect_gender', sa.Boolean(), nullable=True))
    op.add_column('Verification', sa.Column('metadata_incorrect_natlang', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Verification', 'metadata_incorrect_natlang')
    op.drop_column('Verification', 'metadata_incorrect_gender')
    op.drop_column('Verification', 'metadata_incorrect_age')
    # ### end Alembic commands ###
