"""empty message

Revision ID: f2ed1a48ec08
Revises: b4e63ee36fe4
Create Date: 2020-03-26 18:03:48.245718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ed1a48ec08'
down_revision = 'b4e63ee36fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('session_sz', sa.Integer(), nullable=True),
    sa.Column('live_transcribe', sa.Boolean(), nullable=True),
    sa.Column('visualize_mic', sa.Boolean(), nullable=True),
    sa.Column('auto_trim', sa.Boolean(), nullable=True),
    sa.Column('analyze_sound', sa.Boolean(), nullable=True),
    sa.Column('auto_gain_control', sa.Boolean(), nullable=True),
    sa.Column('noise_suppression', sa.Boolean(), nullable=True),
    sa.Column('channel_count', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('blob_slice', sa.Integer(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('video_w', sa.Integer(), nullable=True),
    sa.Column('video_h', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('trim_threshold', sa.Float(), nullable=True),
    sa.Column('too_low_threshold', sa.Float(), nullable=True),
    sa.Column('too_high_threshold', sa.Float(), nullable=True),
    sa.Column('too_high_frames', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Collection', sa.Column('configuration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Collection', 'Configuration', ['configuration_id'], ['id'])
    op.drop_column('Collection', 'has_video')
    op.add_column('Recording', sa.Column('analysis', sa.String(), nullable=True))
    op.add_column('Recording', sa.Column('auto_gain_control', sa.Boolean(), nullable=True))
    op.add_column('Recording', sa.Column('echo_cancellation', sa.Boolean(), nullable=True))
    op.add_column('Recording', sa.Column('end', sa.Float(), nullable=True))
    op.add_column('Recording', sa.Column('has_video', sa.Boolean(), nullable=True))
    op.add_column('Recording', sa.Column('latency', sa.Float(), nullable=True))
    op.add_column('Recording', sa.Column('noise_suppression', sa.Boolean(), nullable=True))
    op.add_column('Recording', sa.Column('start', sa.Float(), nullable=True))
    op.add_column('Recording', sa.Column('wav_path', sa.String(), nullable=True))
    op.drop_column('Recording', 'num_frames')
    op.add_column('Session', sa.Column('has_video', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'has_video')
    op.add_column('Recording', sa.Column('num_frames', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Recording', 'wav_path')
    op.drop_column('Recording', 'start')
    op.drop_column('Recording', 'noise_suppression')
    op.drop_column('Recording', 'latency')
    op.drop_column('Recording', 'has_video')
    op.drop_column('Recording', 'end')
    op.drop_column('Recording', 'echo_cancellation')
    op.drop_column('Recording', 'auto_gain_control')
    op.drop_column('Recording', 'analysis')
    op.add_column('Collection', sa.Column('has_video', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Collection', type_='foreignkey')
    op.drop_column('Collection', 'configuration_id')
    op.drop_table('Configuration')
    # ### end Alembic commands ###
