"""empty message

Revision ID: f41232bd50d7
Revises: 87aace915c65
Create Date: 2021-02-18 14:45:54.486822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41232bd50d7'
down_revision = '87aace915c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Mos', sa.Column('show_text_in_test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Mos', 'show_text_in_test')
    # ### end Alembic commands ###
