"""empty message

Revision ID: f8b54ff0e756
Revises: d846d23a96f4
Create Date: 2020-02-11 22:09:21.384218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b54ff0e756'
down_revision = 'd846d23a96f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Session', 'user', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Session', type_='foreignkey')
    op.drop_column('Session', 'manager_id')
    # ### end Alembic commands ###
