"""empty message

Revision ID: fa3d28c06824
Revises: 7c96aac42013
Create Date: 2021-06-11 18:44:54.107448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3d28c06824'
down_revision = '7c96aac42013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SocialPost', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SocialPost', 'created_at')
    # ### end Alembic commands ###
