"""empty message

Revision ID: fdc3275f48bf
Revises: 1a3fe32041b8
Create Date: 2020-07-14 09:45:17.985140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc3275f48bf'
down_revision = '1a3fe32041b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifier_font', sa.Column('font_family', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifier_font', 'font_family')
    # ### end Alembic commands ###
